<nav>
  <div class="nav">
    <a href="#!" class="brand-logo center">
      AIR V4
    </a>
	<ul>
		<li>
		<a href="#"  data-activates="slide-out" class="button-collapse show-on-large"><i class="material-icons">menu</i></a>
		</li>
		</ul>
		<ul class="right hide-on-med-and-down">
		<li>
			<a href="./login.aspx"><i class="material-icons left">exit_to_app</i>Déconnexion</a>	
		</li>
	</ul>
   
  </div>
</nav>



 <ul id="slide-out" class="side-nav">
    <li>
		<div class="user-view">
			
      
			<a href="#!user"><img class="responsive-img" src="./Images/logo_AIR.jpg"></a>
			
		
			<div class="row">
				<div class="input-field col s12">
					<i class="material-icons prefix">account_circle</i>
					<input disabled id="utilisateur" type="text" class="validate">
				</div>
			</div>

	  </li>

		
        <li>
			
					<a href="./tb.aspx">
					<i class="material-icons prefix">dashboard</i>
					<span class="badge">Tableau de bord</span>
					</a>
				
		</li>

		<li>
			
					<a href="./client_s001.aspx">
					<i class="material-icons prefix">people</i>
					<span class="badge">Client</span>
					</a>
			
		</li>

		<li>
			
					<a href="./agent/agent_s001.aspx">
					<i class="material-icons prefix">group</i>
					<span class="badge">Agent</span>
					</a>
				
		</li>


		<!-- Dropdown Trigger -->
		<li>
  <a class='dropdown-button' href='#' data-activates='menu_admin'><i class="material-icons">settings_applications</i>Administration</a>

  <!-- Dropdown Structure -->
  <ul id='menu_admin' class='dropdown-content'>
    <li><a href="#!"><i class="material-icons">check</i>Autorisations</a></li>
    <li><a href="#!"><i class="material-icons">phonelink_erase</i>Intéruption alerte </a></li>
    <li><a href="#!"><i class="material-icons">sms</i>SMS Manuel</a></li>
	<li><a href="#!"><i class="material-icons">edit</i>Gestion message</a></li>
	<li><a href="#!"><i class="material-icons">face</i>Utilisateur</a></li>
  </ul>
  </li>
		


		
	</ul>

		

  


